name: Deploy React App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Prepare Target Directory
        if: github.event_name == 'push'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.USERNAME }}
          script: |
            rm -rf /home/ubuntu/app/dist
            mkdir -p /home/ubuntu/app/dist

      - name: Deploy React Project To EC2
        if: github.event_name == 'push'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.USERNAME }}
          source: "dist/"
          target: "/home/ubuntu/app"
          overwrite: true

      - name: Recreate Container
        if: github.event_name == 'push'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.USERNAME }}
          script: |
            cd /home/ubuntu/app
            docker compose up -d --force-recreate web
